name: Download Release, Convert Markdown to HTML, and Publish to Confluence

on:
  push:
    branches:
      - main

jobs:
  download_convert_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release assets
        id: get_release_assets
        run: |
          assets_url=$(curl -sH "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest" | \
            jq -r '.assets_url')
          assets_response=$(curl -sH "Authorization: Bearer $GITHUB_TOKEN" "$assets_url")
          asset_url=$(echo "$assets_response" | jq -r '.[0].browser_download_url')
          echo "Download URL: $asset_url"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Download release asset
        run: |
          if [ -n "$asset_url" ]; then
            wget -O release.zip "$asset_url"
            unzip release.zip -d downloaded_assets
          else
            echo "Asset URL is empty. Unable to proceed."
            exit 1
          fi

      - name: Convert Markdown to HTML
        run: |
          pandoc -s -o converted_content.html downloaded_assets/*.md

      - name: Publish to Confluence
        run: |
          # Read the converted HTML content
          html_content=$(cat converted_content.html)

          # Get the current version of the Confluence page
          current_version=$(curl -u $CONFLUENCE_USERNAME:$CONFLUENCE_API_TOKEN -X GET -H 'Content-Type: application/json' \
                              https://jatin-bamel.atlassian.net/wiki/rest/api/content/$CONFLUENCE_PAGE_ID | jq -r '.version.number')

          # Increment the version number for the update
          updated_version=$((current_version + 1))

          # Use cURL to send content to Confluence
          curl -u $CONFLUENCE_USERNAME:$CONFLUENCE_API_TOKEN -X PUT -H 'Content-Type: application/json' \
               -d '{
                     "version": {
                       "number": '$updated_version'
                     },
                     "title": "Your Page Title",
                     "type": "page",
                     "body": {
                       "storage": {
                         "value": "'"$html_content"'",
                         "representation": "storage"
                       }
                     }
                   }' \
               https://jatin-bamel.atlassian.net/wiki/rest/api/content/$CONFLUENCE_PAGE_ID
               https://jatin-bamel.atlassian.net/wiki/rest/api/content/$CONFLUENCE_PAGE_ID

        env:
          CONFLUENCE_USERNAME: jatsingh9696@gmail.com
          CONFLUENCE_API_TOKEN: ATATT3xFfGF03TKfEACLeEGHkY-6qePoYewJ7OpzzRzHQ07ZkFFB5NCDE1pX0PY0O3T8XbZeyOdhbk0XE9eNzvmC8e9EM6iVcks6dV0whIn3NRc81KyJw9ZF2WeoFIAC2r8HYAyPRXaX4FrSwhyar21l-WEO_tVxKrMVB5EFrym9DYgJeyKLYK4=62672B17
          CONFLUENCE_PAGE_ID: "950287"
