name: Download Release

on:
  release:
    types:
      - created

jobs:
  download-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Release
      run: |
        DOWNLOAD_URL="https://github.com/${{ github.repository }}/archive/${{ github.event.release.tag_name }}.tar.gz"
        curl -LJO $DOWNLOAD_URL

    - name: Get Release Notes
      run: RELEASE_NOTES=$(gh release view ${GITHUB_REF#refs/tags/} --json notes --repo $GITHUB_REPOSITORY --template '{{.body}}')

    - name: Print Release Notes
      run: echo "Release Notes: $RELEASE_NOTES"

    - name: Print Message
      run: echo "Release downloaded successfully! Check the artifacts for the downloaded file."
