name: Release Notes Workflow

on:
  push:
    branches:
      - main

jobs:
  download-release-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Release Notes
      id: download-notes
      run: |
        RELEASE_NOTES=$(gh release notes -R $GITHUB_REPOSITORY)
        echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV

  echo-release-notes:
    needs: download-release-notes
    runs-on: ubuntu-latest

    steps:
    - name: Print Release Notes
      run: echo "${{ env.RELEASE_NOTES }}"
