name: Update Confluence on Release

on:
  release:
    types:
      - published

jobs:
  update-confluence:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./publisher/requirements.txt

    - name: Update Confluence on Release
      run: |
        python update_confluence.py "release" "v1.0.0" "Release notes for v1.0.0"
