name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        ls -la
        python -m pip install --upgrade pip
        pip install -r ./publisher/requirements.txt

    - name: Publish MD files to the Confluence space
      env:
        LOGIN: ${{secrets.confluence_login }}
        PASSWORD: ${{secrets.confluence_password }}
       # LOGIN: jatsingh9696@gmail.com
       # PASSWORD: ATATT3xFfGF0geElBSZ7W09Ye56M6M4Hwhr83opRJo48mifJBx5pPfc5bw_ahFgLxHa0GFoTS1eCaA7eqBowmO9mrYdxlhK4vRovBDGfHdfBkuMMrMCViPYyCEz0eGo-00NZVREfcSfywj1HvJo8mfKREyNIYKB0Akz7KPDVWf1FhMtt3giEiYc=6F694965
      run: |
        python3 ./publisher/main.py --login="$LOGIN" --password="$PASSWORD"
