name: Release

on:
 workflow_dispatch:

jobs:
  fetch-latest-release-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: View latest release and store release notes
      run: |
        latest_tag=$(gh release list --limit 1 | awk '{print $1}')
        echo $latest_tag
        RELEASE_NOTES=$(gh release view $latest_tag --json body | jq -r '.body')
        echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    - name: Print Release Notes
      run: echo "${{ env.RELEASE_NOTES }}"
   
