name: Release

on:
 workflow_dispatch:

jobs:
  fetch-latest-release-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: View latest release and store release notes
      run: |
        latest_tag=$(gh release list --limit 1 | awk '{print $1}')
        echo $latest_tag
        gh release view $latest_tag --json body | jq -r .body > release_notes.md
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    - name: Print Release Notes
      run: cat release_notes.md

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert MD to Confluence Markup
      run: |
        pandoc -s release_notes.md -o confluence_markup.txt
        echo test
        cat confluence_markup.txt
    - name: Publish to Confluence
      env:
        LOGIN: jatsingh9696@gmail.com
        PASSWORD: ATATT3xFfGF0FH9mamNdVhcbRQE0d_LYgO1BJT1t0C3-WldfeBZnr7yCkjrr4vnM-g5AJerVge8cASB9nQ4owra1HhugmijtaRzSkDOu7nGJKlDewMKIBAjtdFNnbAU8KDfMG33-45sV1-iuA2NOWS7C1LDEVUIcQXLUn8-XseowIhPUTNRKmiE=B1CA68AB
        CONFLUENCE_URL: https://jatin-bamel.atlassian.net/wiki/rest/api/
        CONFLUENCE_SPACE: jatin
        CONFLUENCE_PARENT_PAGE_ID: 3833948
      run: |
        curl -u "${LOGIN}:${PASSWORD}" -X PUT -H 'Content-Type: application/json' \
          -d '{"version":{"number":your_current_page_version},"title":"Your Page Title","type":"page","body":{"storage":{"value":"$(< confluence_markup.txt)","representation":"storage"}}}' \
          "${CONFLUENCE_URL}content/${CONFLUENCE_PARENT_PAGE_ID}/child/${CONFLUENCE_SPACE}"




