name: Release

on:
 workflow_dispatch:

jobs:
  download-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Release Notes
      run: |
        # Extract tag or branch name from GITHUB_REF
        if [[ "${GITHUB_REF}" == "refs/tags/"* ]]; then
          RELEASE_TAG=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///')
        else
          RELEASE_TAG=$(echo "${GITHUB_REF}" | sed 's/refs\/heads\///')
        fi

        # Retrieve release notes
        RELEASE_NOTES=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${RELEASE_TAG}" | \
          jq -r '.body')
          
        echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Print Release Notes
      run: |
        if [ -n "$RELEASE_NOTES" ]; then
          echo "Release Notes: $RELEASE_NOTES"
        else
          echo "Release Notes not available."
        fi

    - name: Print Message
      run: echo "Release downloaded successfully! Check the artifacts for the downloaded file."
