name: Download Release

on:
  push:
    branches:
      - main

jobs:
  download-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Release
      id: download
      run: |
        # Get the latest release information
        RELEASE_INFO=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest")
        DOWNLOAD_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[0].browser_download_url')
        
        # Download the release asset
        wget "$DOWNLOAD_URL" -O downloaded-release.zip

        # Print some information
        echo "Downloaded the latest release from: $DOWNLOAD_URL"
        echo "Release information: $RELEASE_INFO"
      
    - name: Print Release Path
      run: echo "Release Path: ${{ github.workspace }}/downloaded-release.zip"
