name: Save Release Notes to Git Wiki

on:
  workflow_dispatch:

jobs:
  save-release-notes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # - name: Fetch release notes
    #   run: |
    #     # Use GitHub API to fetch release notes and save to a file
    #     curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
    #       "https://api.github.com/repos/${{ github.repository }}/releases/latest" \
    #       > release_notes.json
    - name: Fetch release body
      run: |
          # Use GitHub API to fetch release notes and save to a file
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest" \
            > release_notes.json
          # Use jq to extract the body from the JSON file and save it to another file
          jq -r '.body' release_notes.json > release_notes_body.md
          
    - name: Release body
      run: |
        cat release_notes_body.md
    
