on:
  workflow_dispatch:

jobs:
  save-release-notes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Fetch release body and save as artifact
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" \
          > release_notes.json
        jq -r '.body' release_notes.json > release_notes_body.md
      - name: Archive release notes
        uses: actions/upload-artifact@v2
        with:
          name: release-notes
          path: release_notes_body.md

  Save Release Notes to Git Wiki:
    runs-on: ubuntu-latest
    needs: save-release-notes
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Retrieve the artifact from the previous job
    - name: Download release notes artifact
      uses: actions/download-artifact@v2
      with:
        name: release-notes
        path: ${{ github.workspace }}

    # Define RELEASE_NOTES variable
    - name: Define RELEASE_NOTES variable
      id: set_release_notes
      run: echo "::set-output name=RELEASE_NOTES::$(cat ${{ github.workspace }}/release_notes_body.md)"

    - name: Use GitHub variable
      run: |
        echo "Release notes: ${{ steps.set_release_notes.outputs.RELEASE_NOTES }}"

    # Other steps in your workflow can now use the RELEASE_NOTES variable
    - name: Debugging
      run: |
        echo "${{ steps.set_release_notes.outputs.RELEASE_NOTES }}" > release_notes.json
        ls -al
        echo "Path to release_notes.json: /home/runner/work/test-git/test-git/release_notes.json"
        echo "Contents of the workspace directory:"
        ls -al "${{ github.workspace }}"
    - name: edit wiki
      run: |
        cp "${{ github.workspace }}/release_notes_body.md" . # Copy the release_notes_body.md file to the current directory

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes"

    - name: Push changes to wiki repo
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ github.repository }}.wiki
        github_token: ${{ secrets.GITHUB_TOKEN }}
