on:
  workflow_dispatch:

jobs:
  save-release-notes-and-push-to-wiki:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Fetch release body and save as artifact
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" \
          > release_notes.json
        jq -r '.body' release_notes.json > release_notes_body.md
        jq -r 'to_entries[] | "\(.key): \(.value)"' release_notes.json > release_notes.md

    - name: Archive release notes
      uses: actions/upload-artifact@v2
      with:
        name: release-notes
        path: |
          release_notes.md
          release_notes_body.md

    - name: Checkout wiki repository
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki

    - name: Download release notes artifact
      uses: actions/download-artifact@v2
      with:
        name: release-notes
        path: ${{ github.workspace }}

    - name: Push to wiki
      run: |
        cd "${{ github.workspace }}"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff-index --quiet HEAD || git commit -m "Add changes" && git push
