name: Save Release Notes to Git Wiki

on:
  workflow_dispatch:

jobs:
  save-release-notes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Fetch release notes
      run: |
        # Use GitHub API to fetch release notes and save to a file
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest" \
          > release_notes.json
      
    - name: Commit and push to Git wiki
      run: |
        git clone https://github.com/${{ github.repository }}.wiki.git wiki || true
        cd wiki
        git pull origin master || true
        cd ..
        
        # Copy release notes to wiki
        cp release_notes.json wiki/
        
        # Commit changes
        cd wiki
        git add release_notes.json
        git commit -m "Update release notes"
        
        # Push changes to Git wiki repository
        git push 
